### ISSUE TITLE
"help wanted" Crash a lot

### ISSUE THREAD

**Issue by Antobm81** [RedBrumbler/SongBrowser#1]
always crashes with it enabled

**Comment by Antobm81** [comment]
to add further details, it would crash if i clicked "Solo" or Party" option in the main menu, but i found a workaround by disabling "open to custom levels" in pinkcore's mod settings

but now that i can get into the menu, only non custom songs load, if i click on a custom song or try to filter them, it crashes

**Comment by RedBrumbler** [comment]
do you have chroma installed ? if so, can you try without it ?

**Comment by Antobm81** [comment]
oddly, it seems to work with chroma disabled. i still wonder why it happens though

**Comment by RedBrumbler** [comment]
my concern is a specific thing pinkcore does, which CJD also does, and if both do it, it can mess it up in some way so without CJD it's "fixed"

the crash also happens to not actually be a songbrowser crash

**Comment by Antobm81** [comment]
if i may ask, what's CJD?

**Comment by RedBrumbler** [comment]
Custom JSON Data

I have just PR'd the fix to the issue that caused this specific crash, so it's out of my hands now, I will be closing this issue because it's actually not related to this mod
