### ISSUE TITLE
Quest2: cannot locate symbol _ZN17RuntimSongLoader...

### ISSUE THREAD

**Issue by Arkenge** [RedBrumbler/SongBrowser#2]
Hi,

I have now more than 400 custom songs, so your mod was exactly what I was looking for :) However, I'm getting an error message while using it on the Quest2.

I have downloaded the last version of your mod from this link, https://github.com/RedBrumbler/SongBrowser/releases/download/v1.0.0/SongBrowser.qmod

I have uploaded it through BFBM, made sure that it was activated, and then loaded Beat Saber on my Quest2. However, I get this error  :
![com beatgames beatsaber-20210828-122537](https://user-images.githubusercontent.com/84845908/131226391-ca00e1b1-4c16-4bd2-a065-e7c49f0dd40d.jpg)

I tried on the BFBM discord, but no one could help. I tried to uninstall/reinstall the mods, same issue. 

If you knew how to solve this, it would be absolutely fantastic!
Thanks in advance

**Comment by RedBrumbler** [comment]
Update your songloader

**Comment by Arkenge** [comment]
Thank you very much. Problem solve! :)
